### ISSUE TITLE
Developer Experience: setup tests

### ISSUE THREAD

**Issue by MichaelBailly** [linagora/esn#11]
### Step by step on how to set up tests for a module: 

1. Create a new webpack config file like [this one](https://github.com/OpenPaaS-Suite/esn-frontend-calendar/blob/d02ba911ed6d9be7194b10ec7a24c93845ff2b7c/webpack.test.js)

2. Copy old test folder from old repository, remove all unnecessary files and leave only frontend test related files there.

3.  Update the [karma.conf.js file](https://github.com/OpenPaaS-Suite/esn-frontend-calendar/blob/c7a23b7c6c6bf4c82b55e59b3c27eb2393eb2032/test/config/karma.conf.js)
 - `config.files` will have a file named index.test.js at top. This file will play the role as our webpack entry point file.
 - Note that we now use FirefoxHeadless instead of PhantomJS.

4. Update package.json:
 - Add this script: `"test": "./node_modules/karma/bin/karma start test/config/karma.conf.js"`

5. Create index.test.js file inside `src` folder. This file will require all necessary dependencies, mdule files & test files. See [here](https://github.com/OpenPaaS-Suite/esn-frontend-calendar/blob/c7a23b7c6c6bf4c82b55e59b3c27eb2393eb2032/src/index.test.js)

6. Try to run the test and fix the problems ( if any )

### Some common problems appear when working on this issue (Updating...)

1. Missing chai / sinon / ...
For those libraries please install them via npm and require them in `index.test.js`

2. `jadeTemplates`
Remove all `jadeTemplates` module since we have loaded all of our pug files via webpack.

3. Unexpected request
 Most likely those unexpected requests should be /api/i18n or /api/jwt/generate. In this case, some `run` functions inside `esn-frontend-common-libs` have caused this. To resolve this, first detect where they have been called.
Eg: For `/api/i18n`, it was called in a file named `i18n-loader.service.js` inside `i18n` module.
Then disable the run function by exclude the file ( If you can ) or, in this case, replace the file with a new mock file. I created a mock file called `i18n-loader.js` inside `mocks` folder in `test`. After that use `NormalModuleReplacementPlugin` of webpack to replace the original file with the mock one.

4. `$q is undefined`
In some test cases, we have some `beforeEach` hooks that are using $q to mock sth. Eg:

var abcMock = {
   get: $q.when({})
};

When webpack wraps things & comes to this point, it will throw an error: `$q is undefined`. `$q` was originally a built-in service of AngularJS therefore we cannot use it without injecting it.

Back to the old days (old code base), we have a file called `injector.js` inside `mocks` folder in `test`. What this file does is: 
 - Declare an AngularJS module `esn.test.injector` & a `run` function. This function will inject dependencies such as `$q` and assign it to global variable.
 - Create a global `beforeEach` hook, which will inject module `esn.test.injector` in every test case.
So theoretically, we will have our `$q` global & no more `$q is undefined`.

However, I discovered that this won't work as expected. The lifecycle of mocha testing should look like this:

`beforeEach global hook`
       `beforeEach for test file`
              `beforeEach in describe block`
                        `test case (it)`

So the `run` function of `esn.test.injector` won't run right after the beforeEach global hook executed, but instead run when it comes to test case. Therefore in `beforeEach` hook, `$q` is still undefined.

To make things work, I came up with a solution. I require & use `$q` from `node_modules/q/q.js` as global $q.

var $q = require('q/q.js');
window.$q = $q;

Please let me know if you have any better approach.

5. Unknown provider
Most likely it is because we have missed to inject some modules to our tests. Eg: `esn.calendar.libs` is a new module that was created to store services & common functions. To use them you need to inject `esn.calendar.libs` to our tests:
`angular.mock.module('esn.calendar.libs')`

**Comment by piavgh** [comment]
@ppppbn : Here are some of the other issues that I met, please provide the solution for these also (if you have):

- No more request expected
- $q is undefined
- esnConfig(...) is undefined

**Comment by itswillta** [comment]
FYI, you should use the newer versions of `sinon` and `sinon-chai` that we previously used:

```
    "sinon": "6.1.4",
    "sinon-chai": "3.2.0",
```

**Comment by itswillta** [comment]
Regarding the problem around `$q` in `beforeEach` blocks, use `$q = angular.injector(['ng']).get('$q');`. That should solve the problem.

More information about `angular.injector` here: https://docs.angularjs.org/api/ng/function/angular.injector

**Comment by itswillta** [comment]
Regarding the `esnConfig` errors, just ignore the `i18n.run.js` file in `esn-frontend-common-libs`. You can use a Webpack plugin called [`ignore-loader`](https://www.npmjs.com/package/ignore-loader) to do that:

```
module: {
    rules: [
      { test: /\.run.js$/,
        loader: 'ignore-loader',
        include: [
          path.resolve(__dirname, 'node_modules/esn-frontend-common-libs/src/frontend/js/modules/i18n/i18n.run.js')
        ]
      }
    ]
  }
```

**Comment by piavgh** [comment]
@ppppbn : related to the promise issues, the way you used setTimeout to make the test passed might be wrong.
It was passed because the expect statements did not run.

You can verify this by changing `to.equal` to `to.not.equal` or `.to.have.calledOnce` to `.to.not.have.calledOnce`
If it also passes, the setTimeout is wrong.

**Comment by rezk2ll** [comment]
error when attempting to spy on something inside $rootScope:
example:

```js
$rootScope.$broadcast = sinon.spy();
expect($rootScope.$broadcast).to.not.have.been.called;
```
will yield the following error:
```
 $rootScope.$broadcast(...) is undefined
```

**solution**:

create the spy in a different way:
```js
 var spy = sinon.spy($rootScope, '$broadcast');
 expect(spy).to.not.have.been.called;
```

**Comment by rezk2ll** [comment]
when encountering `$window.$ is undefined` in tests you can still fix it by adding the following rule to `webpack.test.js`:

```js
{
  test: require.resolve('jquery'),
  loader: 'expose-loader',
  options: {
    exposes: '$'
  }
}
```

**Comment by rezk2ll** [comment]
when trying to spy on the `window.location` functions like `window.location.reload`, like this example:
```js
$window.location.reload = sinon.spy();
esnLoginSuccessService();

expect($window.location.reload).to.have.been.calledOnce;
```

you will get the following error:
```
 "reload" is read-only
```

when trying to modify the whole `window.location` you will cause the page to reload and abort the test with this error
`some of your tests did a full page reload!`, like:

```js
$window.location= {
  reload: sinon.spy()
}
```

**workaround**

provide your own `$window` in a `beforeEach` statement

```js
beforeEach(function () {
  angular.mock.module('yourmodule', function ($provide) {
    let $window = { location: { reload: sinon.spy() } };
    $provide.value('$window', $window);
    $window.onbeforeunload = sinon.spy();
  });
});
```

**Comment by itswillta** [comment]
I'm closing this issue since there are already "Setup tests" issues in each of the repositories already.
