### ISSUE TITLE
Setup CI for SPAs/Libraries

### ISSUE THREAD

**Issue by tuanlc** [linagora/esn#29]
Reference PRs:
- https://github.com/OpenPaaS-Suite/esn-frontend-admin/pull/51

List of SPAs / Libraries:
- [x] [esn-frontend-common-libs](https://github.com/OpenPaaS-Suite/esn-frontend-common-libs) (@pbson is doing it)
- [x] [esn-frontend-account](https://github.com/OpenPaaS-Suite/esn-frontend-account) (@pbson is doing it)
- [x] [esn-frontend-admin](https://github.com/OpenPaaS-Suite/esn-frontend-admin) (@huy-ta is doing it)
- [x] [esn-frontend-contacts](https://github.com/OpenPaaS-Suite/esn-frontend-contacts) (@huy-ta is doing it)
- [x] [esn-frontend-calendar](https://github.com/OpenPaaS-Suite/esn-frontend-calendar) (@pbson is doing it)
- [x] [esn-frontend-mailto](https://github.com/OpenPaaS-Suite/esn-frontend-mailto) (@huy-ta is doing it)
- [x] [esn-frontend-linshare](https://github.com/OpenPaaS-Suite/esn-frontend-linshare) (@pbson is doing it)
- [x] [esn-frontend-inbox-calendar](https://github.com/OpenPaaS-Suite/esn-frontend-inbox-calendar) (@huy-ta is doing it)
- [x] [esn-frontend-inbox-linshare](https://github.com/OpenPaaS-Suite/esn-frontend-inbox-linshare) (@pbson is doing it)
- [x] [esn-frontend-videoconference-calendar](https://github.com/OpenPaaS-Suite/esn-frontend-videoconference-calendar) (@huy-ta is doing it)
- [x] [esn-frontend-account-inbox](https://github.com/OpenPaaS-Suite/esn-frontend-account-inbox) (@pbson is doing it)
- [x] [esn-api-client](https://github.com/OpenPaaS-Suite/esn-api-client) (@huy-ta is doing it)
- [x] [esn-dav-import-client](https://github.com/OpenPaaS-Suite/esn-dav-import-client) (@pbson is doing it)

**Comment by aduprat** [comment]
Hi,

This task is a good start for the team in order to learn Jenkinsfile.

We are currently working in a soft way to handle new repository on the CI part;
it's not done yet, so feel free to ask us in order to add new items (repository) in it.
