### ISSUE TITLE
Create the esn-frontend-mailto-handler module

### ISSUE THREAD

**Issue by MichaelBailly** [linagora/esn#3]
Details: https://ci.linagora.com/linagora/lgs/openpaas/esn/-/wikis/Week-by-Week-Activity#esn-frontend-mailto-handler

**Comment by chamerling** [comment]
Here is what can be done: 

The `opInboxCompose` is defined in the `esn-frontend-inbox` SPA and used only in this SPA. If we create a directive with the same name in the `esn-frontend-mailto-handler` but with a different behavior (ie open the mailto SPA) and then use it in other SPAs, we easily implement the mailto-handler without touching all the current places where `opInboxCompose` is used.

What is missing is a service which provides the mailto SPA URL, but which is currently discussed in the Service Discovery tasks.

@MichaelBailly good for you?

**Comment by MichaelBailly** [comment]
I agree with that behaviour.

For now, we'll use "/mailto" as the mailto SPA URL. We'll add dynamic handling when the Application Discovery is up.
