### ISSUE TITLE
Fix RabbitMQ messages read in ESN

### ISSUE THREAD

**Issue by MichaelBailly** [linagora/esn#33]
With the help of @chibenwa , have a diagnostic of RabbitMQ queues and understand why some of them are not dequeued.

![image](https://user-images.githubusercontent.com/1465817/92479835-59d21880-f1e4-11ea-9375-3937ae681ac9.png)

RabbitMQ management console access have been sent to Benoit.

**Comment by tuanlc** [comment]
More detail information: https://ci.linagora.com/linagora/lgs/openpaas/esn/issues/3028

**Comment by MichaelBailly** [comment]
@tuanlc  can we close this issue ?

**Comment by tuanlc** [comment]
@MichaelBailly yes. There is another issue need to be checked. I created the issue: https://github.com/OpenPaaS-Suite/esn/issues/34

So I will close this one!
