### ISSUE TITLE
Fix noanimation issue for all frontend projects

### ISSUE THREAD

**Issue by piavgh** [linagora/esn#35]
Recently, we had the issue https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/127

The root cause of that issue is that the attribute `noanimation` has no value.

We need to update it to `noanimation="noanimation"` for all projects

**Comment by itswillta** [comment]
Also you can refer to this for more details: https://github.com/angular-ui/ui-router/blob/2523bbdb5542483a489c22804f1751b8b9f71703/src/viewDirective.js#L146
