### ISSUE TITLE
Update the Jenkinsfile to force the CI to fetch the newest packages online when running 'npm install'

### ISSUE THREAD

**Issue by itswillta** [linagora/esn#36]
Sometimes there's a pull request that requires another pull request from another repository to be merged, but the CI build is using the same Docker container, which prevents using only `npm install` from fetching the newer packages. The solution is to use `npm install -f` instead to always force fetching the newest packages online.

**Comment by tuanlc** [comment]
- [x] esn-frontend-group 
- [x] esn-frontend-calendar 
- [x] esn-frontend-account-inbox 
- [x] esn-frontend-inbox 
- [x] esn-frontend-mailto 
- [x] esn-frontend-common-libs 
- [x]  esn-frontend-admin 
- [x] esn-frontend-contacts 
- [x] esn-frontend-inbox-james 
- [x] esn-api-client 
- [x] esn-frontend-account 
- [x] esn-dav-import-client 
- [x] esn-frontend-mailto-handler 
- [x] esn-frontend-login 
- [x] esn-frontend-inbox-calendar 
- [x] esn-frontend-calendar-public 
- [x] esn-frontend-linshare 
- [x] esn-frontend-videoconference-calendar 
- [x] esn-frontend-inbox-linshare
