### ISSUE TITLE
Build the docker image for frontend SPA

### ISSUE THREAD

**Issue by MichaelBailly** [linagora/esn#39]
SPA:

- esn-frontend-account. Path = "/account/"
- esn-frontend-admin. Path = "/admin/"
- esn-frontend-calendar. Path = "/calendar/"
- esn-frontend-calendar-public. Path = "/excal/"
- esn-frontend-contacts. Path = "/contacts/"
- esn-frontend-inbox. Path = "/inbox/"
- esn-frontend-mailto. Path = "/mailto/"

Build steps:

- git clone
- use branch **main**
- npm i
- build:
Env variables:
* BASE_HREF : this is the root path of the app. Example: esn-frontend-calendar, BASE_HREF="/calendar/"
* APP_GRID_ITEMS: the appliaction grid icons to show, with URLs to application web interfaces.
Default:

```
APP_GRID_ITEMS="[{ \"name\": \"Calendar\", \"url\": \"/calendar/\" }, { \"name\": \"Contacts\", \"url\": \"/contacts/\" }, { \"name\": \"Inbox\", \"url\": \"/inbox/\" }]"
```

Static assets are put in the **dist** folder. GET /calendar/ -> dist/index.html

repository https://github.com/OpenPaaS-Suite/openpaas-front

Next steps:

- automate docker image build when there is a new commit on the main branch of any of the projects, publish on dockerhub
- update openpaas-platform-docker-dev
- build on a specific version

**Comment by tanandy** [comment]
@MichaelBailly can you link the repo where i will store the Dockerfile for ESN frontend (all in one)

1 Dockerfile for 1 all in one frontend (account,admin, calendar,calendar-public,contacts,inbox,mailto)

**Comment by MichaelBailly** [comment]
@tanandy issue updated

**Comment by tanandy** [comment]
@MichaelBailly can you tell me for the line

 BASE_HREF : this is the root path of the app. Example: esn-frontend-calendar, BASE_HREF="/calendar/"

i dont see any mention in inbox README, can you confirm i can go for:


* Inbox
```bash
APP_GRID_ITEMS="[{ \"name\": \"Calendar\", \"url\": \"/calendar/\" }, { \"name\": \"Contacts\", \"url\": \"/contacts/\" }, { \"name\": \"Inbox\", \"url\": \"/inbox/\" }]" BASE_HREF="/inbox/" npm run build:prod
```

* Mailto
```bash
APP_GRID_ITEMS="[{ \"name\": \"Calendar\", \"url\": \"/calendar/\" }, { \"name\": \"Contacts\", \"url\": \"/contacts/\" }, { \"name\": \"Inbox\", \"url\": \"/inbox/\" }]" BASE_HREF="/mailto/" npm run build:prod
```

* Account
```bash
APP_GRID_ITEMS="[{ \"name\": \"Calendar\", \"url\": \"/calendar/\" }, { \"name\": \"Contacts\", \"url\": \"/contacts/\" }, { \"name\": \"Inbox\", \"url\": \"/inbox/\" }]" BASE_HREF="/account/" npm run build:prod
```
* Contacts
```bash
APP_GRID_ITEMS="[{ \"name\": \"Calendar\", \"url\": \"/calendar/\" }, { \"name\": \"Contacts\", \"url\": \"/contacts/\" }, { \"name\": \"Inbox\", \"url\": \"/inbox/\" }]" BASE_HREF="/contacts/" npm run build:prod
```
* Calendar
```bash
APP_GRID_ITEMS="[{ \"name\": \"Calendar\", \"url\": \"/calendar/\" }, { \"name\": \"Contacts\", \"url\": \"/contacts/\" }, { \"name\": \"Inbox\", \"url\": \"/inbox/\" }]" BASE_HREF="/calendar/" npm run build:prod
```

* Calendar Public
```bash
APP_GRID_ITEMS="[{ \"name\": \"Calendar\", \"url\": \"/calendar/\" }, { \"name\": \"Contacts\", \"url\": \"/contacts/\" }, { \"name\": \"Inbox\", \"url\": \"/inbox/\" }]" BASE_HREF="/excal/" npm run build:prod
```

* Admin
```bash
APP_GRID_ITEMS="[{ \"name\": \"Calendar\", \"url\": \"/calendar/\" }, { \"name\": \"Contacts\", \"url\": \"/contacts/\" }, { \"name\": \"Inbox\", \"url\": \"/inbox/\" }]" BASE_HREF="/admin/" npm run build:prod
```

**Comment by tanandy** [comment]
https://github.com/OpenPaaS-Suite/openpaas-front/blob/main/Dockerfile
