### ISSUE TITLE
[linagora.esn.group] Provide a better API for mailing-lists

### ISSUE THREAD

**Issue by MichaelBailly** [linagora/esn#40]
ESN group members can be either:

* users
* groups
* email addresses

Right now, it's up to the client to tell the server what type of member is, by issuing a first request to have member type for an email address,a nd a second request to do whatever modification is needed on the group.

This leads to inconsistencies. Example:

- a group G1 is created with a member which is { objectType: 'email', id: 'test@acme.org' }
- a user whose email address is test@acme.org login to the platform

Now when updating G1, the client will do:
- what is the objectType of 'test@acme.org' -> { objectType; 'user', id: 'id1' }
- update group G1, remove user id1 -> id1 is not part of the group

**Comment by rouazana** [comment]
Some old tickets about the previous API: https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.group/issues?scope=all&utf8=%E2%9C%93&state=all&author_username=rouazana

**Comment by alagane** [comment]
For the given test case, a solution could be to replace all occurrences of  `test@acme.org` email members to the corresponding user member when the user logs in?

Also the issue https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.group/issues/71 could help removing users by email (instead of just removing emails by email)

**Comment by alagane** [comment]
I don't know about the `remove u1` cases, but I think it should look like this
![image.png](https://images.zenhubusercontent.com/5730988ebf93871ccd9ab837/abb2d083-f51f-4bcc-ad08-b441db65751e)

**Comment by alagane** [comment]
Merge request related: https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.group/merge_requests/123

**Comment by alagane** [comment]
Merge request related: https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.group/merge_requests/124

**Comment by alagane** [comment]
Second merge request related: https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.group/merge_requests/125
